spring.application.name=aisamples

spring.ai.chat.client.enabled=false
# Open Ai Configuration
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o
spring.ai.openai.chat.options.temperature=0.7
spring.ai.openai.chat.options.max-tokens=10000

# Anthropic Claude configuration
spring.ai.anthropic.api-key={ANTHROPIC_API_KEY}
spring.ai.anthropic.chat.options.model=claude-sonnet-4-6
#spring.autoconfigure.exclude=org.springframework.ai.model.anthropic.autoconfigure.AnthropicChatAutoConfiguration


#Config for MCP server
spring.main.web-application-type=none
spring.ai.mcp.server.studio=true
spring.ai.mcp.server.name=spring-io-test-mcp
spring.ai.mcp.server.version=0.0.1
spring.ai.mcp.server.request-timeout=30s

#disable banner and logging for studio transport
spring.main.banner-mode=off
logging.level.root=OFF
